# Generated by Django 3.2.7 on 2023-03-06 17:21

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=mainapp.models.upload_location, width_field='width_field'),
        ),
    ]
