# Generated by Django 3.2.7 on 2023-03-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20230308_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
