# Generated by Django 3.2.7 on 2023-03-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_post_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title1',
            new_name='title2',
        ),
    ]
