# Generated by Django 3.2.7 on 2023-03-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20230308_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title1',
            new_name='jetson',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_name',
        ),
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
