# Generated by Django 3.2.7 on 2023-03-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20230308_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('B', 'Books'), ('C', 'Clothing')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
