# Generated by Django 3.2.7 on 2023-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='camera_height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='distance_to_door',
        ),
        migrations.RemoveField(
            model_name='post',
            name='door_with',
        ),
        migrations.RemoveField(
            model_name='post',
            name='jetson',
        ),
        migrations.RemoveField(
            model_name='post',
            name='site',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='zoom_perc',
        ),
        migrations.AddField(
            model_name='post',
            name='Camera_Position_Image',
            field=models.ImageField(blank=True, null=True, upload_to='mainapp/static/mainapp/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Facebox_Switch_location_image',
            field=models.ImageField(blank=True, null=True, upload_to='mainapp/static/mainapp/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Image_of_signage_in_doorway_image',
            field=models.ImageField(blank=True, null=True, upload_to='mainapp/static/mainapp/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Legal_Entity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Property_Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Router_location_image',
            field=models.ImageField(blank=True, null=True, upload_to='mainapp/static/mainapp/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_camera_set',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_checks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_extra1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_extra2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_instaler',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_night',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_parametrs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_safr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Town_Postcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
