# Generated by Django 3.2.7 on 2023-03-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20230319_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Legal_Entity',
        ),
    ]
