# Generated by Django 3.2.7 on 2023-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_post_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Legal_Entity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
