# Generated by Django 3.2.7 on 2023-03-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_post_legal_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
