# Generated by Django 3.2.7 on 2023-04-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_rename_test_checks_post_are_alerts_working_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='field_for_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
