# Generated by Django 3.2.7 on 2023-04-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_post_field_for_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Camera_Name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
