# Generated by Django 3.2.7 on 2023-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_post_camera_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Camera_Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
