# Generated by Django 3.2.7 on 2023-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_post_legal_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Camera_Position_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Facebox_Switch_location_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image_of_signage_in_doorway_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Legal_Entity',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Router_location_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
