# Generated by Django 3.2.7 on 2023-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20230424_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=500, null=True)),
                ('property', models.CharField(blank=True, max_length=500, null=True)),
                ('town', models.CharField(blank=True, max_length=500, null=True)),
                ('postcode', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
