# Generated by Django 3.2.7 on 2023-04-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Company',
        ),
        migrations.AlterField(
            model_name='property',
            name='company',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='phone_number',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='postcode',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='town',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
