# Generated by Django 3.2.7 on 2023-04-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20230426_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
