# Generated by Django 3.2.7 on 2023-04-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_post_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='company',
            new_name='Legal_Entity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
    ]
