# Generated by Django 3.2.7 on 2023-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20230427_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='town',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
