# Generated by Django 3.2.7 on 2023-04-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_post_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Camera_Name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='Legal_Entity',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='property',
            field=models.CharField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='town',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='Legal_Entity',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
