# Generated by Django 3.2.7 on 2023-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20230428_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Legal_Entity',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='property',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
