# Generated by Django 3.2.7 on 2023-05-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20230428_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postcode',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
