# Generated by Django 3.2.7 on 2023-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20230428_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Town_Postcode',
        ),
        migrations.AddField(
            model_name='post',
            name='aspect_of_door',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='confirm_video_recorded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='door_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='internet_speed_test',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='light_meter_reading_inside',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postcode',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
