# Generated by Django 3.2.7 on 2023-05-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20230504_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='face_box_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
