# Generated by Django 3.2.7 on 2023-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_auto_20230506_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Photo_of_camera',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Photo_of_router',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Photo_of_switch',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
