# Generated by Django 3.2.7 on 2023-05-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20230512_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Town_Postcode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
